blank_issues_enabled: true
contact_links:
  - name: Community Discussions
    url: https://github.com/mateusfg7/Noisekun/discussions
    about: Do you have any questions about the project/website? Open a discussion in the Discussions tab!

