name: "[CI] Push Main"

on:
  push:
    branches:
      - main

jobs:
  check-changed-files:
    name: Check changed files
    runs-on: ubuntu-latest
    outputs:
      isCodeRelatedFilesChanged: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v36
        with:
          since_last_remote_commit: true
          files: |
            src/**
            public/**
            tailwind.config.js
            postcss.config.js
            next.config.js
            package.json
            tsconfig.json

  call-metrics-generator:
    name: Generate pagespeed metrics
    uses: mateusfg7/mfg-b/.github/workflows/pagespeed-metrics.yml@main
    needs: check-changed-files
    if: needs.check-changed-files.outputs.isCodeRelatedFilesChanged == 'true'
    secrets: inherit
    with:
      target: https://noisekun.vercel.app
      pwa: true
  
  call-release:
    name: Create a new release
    uses: mateusfg7/mfg-b/.github/workflows/release.yml@main
    secrets: inherit
    
