name: 'Release and deploy'

on:
  workflow_call:
  workflow_dispatch:

jobs:
  sync-tag:
    name: Sync Tag with Package version
    runs-on: ubuntu-22.04
    outputs:
      isReleaseNew: ${{ steps.bump_tag.outputs.isNew }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'main'

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Install PNPM
        run: npm i -g pnpm

      - name: Install Packages
        run: pnpm i --dev

      - name: Bump Tag
        id: bump_tag
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOWS_TOKEN }}
        run: |
          pnpm bump-tag &&\
            echo "isNew=true" >> "$GITHUB_OUTPUT" ||\
            echo "isNew=false" >> $GITHUB_OUTPUT

  changelog:
    name: Changelog
    runs-on: ubuntu-latest
    needs: sync-tag
    if: needs.sync-tag.outputs.isReleaseNew == 'true'
    outputs:
      changelog: ${{ steps.github_release.outputs.changelog }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'main'
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Setup git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Update CHANGELOG.md
        run: |
          npx conventional-changelog-cli -p conventionalcommits -i CHANGELOG.md -s -r 0 &&\
            git add CHANGELOG.md &&\
            git commit -m "docs(CHANGELOG): v$(git describe --tags --abbrev=0)" &&\
            git push

      - name: Build Changelog
        id: github_release
        run: |
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$(npx conventional-changelog-cli --preset conventionalcommits -r 2)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  release:
    name: Release
    needs: changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'main'
      - name: Get tag
        id: get_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
      - name: Create Release
        uses: mikepenz/action-gh-release@v1 #softprops/action-gh-release
        with:
          body: ${{ needs.changelog.outputs.changelog }}
          tag_name: ${{ steps.get_tag.outputs.tag }}

  rebase-to-prod:
    name: Rebase to Prod
    needs: changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: 'prod'
      - name: Setup git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Fetch Main
        run: git fetch origin main:main
      - name: Rebase Main -> Prod
        run: git rebase main && git push
